# Generated by Django 3.0.1 on 2019-12-26 19:37

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('language', models.CharField(max_length=500)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Add_hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pin', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('star', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Add_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Add_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('bus_distance', models.IntegerField()),
                ('train_distance', models.IntegerField()),
                ('flight_distance', models.IntegerField()),
                ('bus_fare', models.IntegerField()),
                ('train_fare', models.IntegerField()),
                ('flight_fare', models.IntegerField()),
                ('bus_duration', models.DurationField()),
                ('train_duration', models.DurationField()),
                ('flight_duration', models.DurationField()),
                ('visiting_places', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='guide',
        ),
    ]
